version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  lint-and-ts:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm run typescript
workflows:
    build-and-test:
      jobs:
        - lint-and-ts
        
